"""
Synthetic data generator for the Compound Risk Intelligence Platform.

=====================================================================
IMPORTANT: This is 100% SYNTHETIC data.
We have no access to real plant sensors, SCADA, permit-to-work systems,
or maintenance logs. Everything below is generated by us to demonstrate
the compound-risk fusion logic. It is NOT validated against any real
industrial site and must never be presented as real plant data.
=====================================================================

What this module produces, per simulated "tick":
  1. Gas/IoT sensor readings (ppm) for 5 plant zones. Normally fluctuate
     inside a safe band, but a zone can be told to trend upward toward the
     lower explosive limit (LEL) over N ticks so we can script a demo.
  2. Permit records: hot work, confined space entry, general maintenance.
     Each carries zone_id, type, start/end time, and a fire-watch flag.
  3. Maintenance tasks (with due date + completion, so we can flag
     "overdue") and shift roster entries (start/end, so we can flag a
     "long consecutive shift" as a fatigue-risk proxy).

Everything is deterministic for a given seed, so a rehearsed demo replays
identically every time.

Public surface used by the FastAPI layer (built later):
  plant = build_demo_scenario(seed=42)   # or SyntheticPlant(seed=...)
  plant.advance_tick()                    # step the simulation one tick
  plant.get_current_state()               # -> plain dict, JSON-friendly
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Optional

# --- Simulated time model -------------------------------------------------
# Each tick represents a fixed slice of wall-clock time. Keeping this fixed
# and deterministic means permit/maintenance/shift timestamps are reproducible.
SIM_START = datetime(2025, 1, 15, 6, 0, 0)  # start of a morning shift
MINUTES_PER_TICK = 15  # one tick = 15 simulated minutes

# --- Gas trend / detection tuning ----------------------------------------
GAS_HISTORY_LEN = 12  # how many recent ppm readings we keep per zone


@dataclass
class GasConfig:
    """Tuning for a single zone's gas behaviour (ppm = parts per million)."""

    baseline_ppm: float = 10.0          # normal resting concentration
    noise_amplitude: float = 1.5        # +/- random fluctuation each tick
    hard_threshold_ppm: float = 50.0    # single-sensor alarm level (20% LEL)
    lel_ppm: float = 100.0              # lower explosive limit reference


@dataclass
class GasTrend:
    """An upward gas trend scripted to start at a given tick."""

    start_tick: int
    rate_ppm_per_tick: float
    cap_ppm: Optional[float] = None  # plateau ceiling once reached


@dataclass
class Zone:
    zone_id: str
    name: str
    x: float  # normalized floorplan coordinate (0-1)
    y: float


@dataclass
class Permit:
    permit_id: str
    zone_id: str
    permit_type: str  # "hot_work" | "confined_space" | "general_maintenance"
    start_tick: int
    end_tick: int
    fire_watch_logged: bool


@dataclass
class MaintenanceTask:
    task_id: str
    zone_id: str
    description: str
    due_tick: int
    completed: bool = False
    completed_tick: Optional[int] = None


@dataclass
class Shift:
    shift_id: str
    zone_id: str
    worker_id: str
    start_tick: int
    end_tick: int  # scheduled end


# A scheduled event is just "at this tick, mutate the plant this way".
@dataclass
class ScheduledEvent:
    tick: int
    action: str          # human-readable label (handy for logs/debug)
    apply: "callable"     # fn(plant) -> None


# --- Default plant layout (5 zones) --------------------------------------
DEFAULT_ZONES = [
    Zone("zone-1", "Storage Tank Farm", 0.15, 0.25),
    Zone("zone-2", "Compressor House", 0.45, 0.20),
    Zone("zone-3", "Process Unit B", 0.70, 0.45),   # demo hot-work zone
    Zone("zone-4", "Loading Bay", 0.30, 0.70),
    Zone("zone-5", "Utilities / Boiler", 0.75, 0.78),
]

# Fatigue-risk threshold: a continuous shift longer than this is flaggable.
LONG_SHIFT_HOURS = 12.0


class SyntheticPlant:
    """
    Stateful synthetic plant. Advance it one tick at a time and read the
    current state as plain dicts. Deterministic for a given seed.
    """

    def __init__(
        self,
        seed: int = 42,
        zones: Optional[list[Zone]] = None,
        gas_config: Optional[GasConfig] = None,
    ):
        self.seed = seed
        self.rng = random.Random(seed)
        self.gas_config = gas_config or GasConfig()
        self.zones: list[Zone] = zones or [
            Zone(z.zone_id, z.name, z.x, z.y) for z in DEFAULT_ZONES
        ]

        self.tick: int = 0

        # Gas state
        self.gas_ppm: dict[str, float] = {
            z.zone_id: self.gas_config.baseline_ppm for z in self.zones
        }
        self.gas_trends: dict[str, GasTrend] = {}
        self.gas_history: dict[str, list[float]] = {
            z.zone_id: [self.gas_config.baseline_ppm] for z in self.zones
        }

        # Records
        self.permits: list[Permit] = []
        self.maintenance_tasks: list[MaintenanceTask] = []
        self.shifts: list[Shift] = []

        # Scripted events keyed by tick
        self.scheduled_events: list[ScheduledEvent] = []

        self._seed_baseline_records()

    # ------------------------------------------------------------------ #
    # Time helpers
    # ------------------------------------------------------------------ #
    def tick_to_time(self, tick: int) -> datetime:
        return SIM_START + timedelta(minutes=MINUTES_PER_TICK * tick)

    @property
    def now(self) -> datetime:
        return self.tick_to_time(self.tick)

    # ------------------------------------------------------------------ #
    # Baseline (benign) records so the plant isn't empty at tick 0
    # ------------------------------------------------------------------ #
    def _seed_baseline_records(self) -> None:
        # A couple of benign permits elsewhere - correctly run, with fire watch.
        self.permits.append(
            Permit("PTW-1001", "zone-1", "general_maintenance",
                   start_tick=0, end_tick=40, fire_watch_logged=True)
        )
        self.permits.append(
            Permit("PTW-1002", "zone-5", "confined_space",
                   start_tick=2, end_tick=26, fire_watch_logged=True)
        )

        # Maintenance tasks: one already overdue in zone-2, others fine.
        self.maintenance_tasks.extend([
            MaintenanceTask("MT-2001", "zone-2",
                            "Compressor seal inspection",
                            due_tick=-4, completed=False),   # overdue at start
            MaintenanceTask("MT-2002", "zone-4",
                            "Loading arm calibration",
                            due_tick=50, completed=False),
            MaintenanceTask("MT-2003", "zone-3",
                            "Relief valve check",
                            due_tick=8, completed=False),
        ])

        # Shift roster. One worker on a long shift (started before sim, i.e.
        # a night-into-day carryover) that trips the fatigue proxy mid-run.
        self.shifts.extend([
            # started 11h before SIM_START -> crosses 12h during the run
            Shift("SH-3001", "zone-3", "W-042",
                  start_tick=-44, end_tick=12),
            Shift("SH-3002", "zone-1", "W-108",
                  start_tick=0, end_tick=32),
        ])

    # ------------------------------------------------------------------ #
    # Scenario scripting helpers
    # ------------------------------------------------------------------ #
    def schedule(self, tick: int, action: str, apply) -> None:
        self.scheduled_events.append(ScheduledEvent(tick, action, apply))

    def open_permit(self, permit: Permit) -> None:
        self.permits.append(permit)

    def start_gas_trend(self, zone_id: str, rate_ppm_per_tick: float,
                        cap_ppm: Optional[float] = None) -> None:
        self.gas_trends[zone_id] = GasTrend(
            start_tick=self.tick,
            rate_ppm_per_tick=rate_ppm_per_tick,
            cap_ppm=cap_ppm,
        )

    # ------------------------------------------------------------------ #
    # Core simulation step
    # ------------------------------------------------------------------ #
    def advance_tick(self) -> dict:
        """Advance the simulation by one tick and return the new state."""
        self.tick += 1

        # 1) Fire any scripted events for this tick (deterministic order).
        for ev in [e for e in self.scheduled_events if e.tick == self.tick]:
            ev.apply(self)

        # 2) Update gas readings for every zone.
        for z in self.zones:
            self.gas_ppm[z.zone_id] = self._next_gas_value(z.zone_id)
            hist = self.gas_history[z.zone_id]
            hist.append(self.gas_ppm[z.zone_id])
            if len(hist) > GAS_HISTORY_LEN:
                del hist[0:len(hist) - GAS_HISTORY_LEN]

        return self.get_current_state()

    def _next_gas_value(self, zone_id: str) -> float:
        cfg = self.gas_config
        noise = self.rng.uniform(-cfg.noise_amplitude, cfg.noise_amplitude)
        value = cfg.baseline_ppm + noise

        trend = self.gas_trends.get(zone_id)
        if trend is not None and self.tick >= trend.start_tick:
            ramp = (self.tick - trend.start_tick) * trend.rate_ppm_per_tick
            value = cfg.baseline_ppm + ramp + noise
            if trend.cap_ppm is not None:
                value = min(value, trend.cap_ppm + noise)

        return round(max(0.0, value), 2)

    # ------------------------------------------------------------------ #
    # Derived flags
    # ------------------------------------------------------------------ #
    def _is_trending(self, zone_id: str) -> bool:
        """True if the last few readings show a sustained rise."""
        hist = self.gas_history[zone_id]
        if len(hist) < 4:
            return False
        recent = hist[-4:]
        rises = sum(1 for a, b in zip(recent, recent[1:]) if b - a > 1.0)
        return rises >= 3

    def _permit_active(self, p: Permit) -> bool:
        return p.start_tick <= self.tick <= p.end_tick

    def _task_overdue(self, t: MaintenanceTask) -> bool:
        return (not t.completed) and (self.tick > t.due_tick)

    def _shift_hours(self, s: Shift) -> float:
        elapsed_ticks = self.tick - s.start_tick
        return round(elapsed_ticks * MINUTES_PER_TICK / 60.0, 2)

    def _shift_active(self, s: Shift) -> bool:
        return s.start_tick <= self.tick <= s.end_tick

    # ------------------------------------------------------------------ #
    # State snapshot (plain dicts, JSON-friendly)
    # ------------------------------------------------------------------ #
    def get_current_state(self) -> dict:
        cfg = self.gas_config

        gas_readings = []
        for z in self.zones:
            gas_readings.append({
                "zone_id": z.zone_id,
                "ppm": self.gas_ppm[z.zone_id],
                "hard_threshold_ppm": cfg.hard_threshold_ppm,
                "lel_ppm": cfg.lel_ppm,
                "trending_up": self._is_trending(z.zone_id),
                "over_hard_threshold": self.gas_ppm[z.zone_id] >= cfg.hard_threshold_ppm,
                "recent_history": list(self.gas_history[z.zone_id]),
            })

        permits = []
        for p in self.permits:
            permits.append({
                "permit_id": p.permit_id,
                "zone_id": p.zone_id,
                "type": p.permit_type,
                "start_time": self.tick_to_time(p.start_tick).isoformat(),
                "end_time": self.tick_to_time(p.end_tick).isoformat(),
                "fire_watch_logged": p.fire_watch_logged,
                "active": self._permit_active(p),
            })

        maintenance = []
        for t in self.maintenance_tasks:
            maintenance.append({
                "task_id": t.task_id,
                "zone_id": t.zone_id,
                "description": t.description,
                "due_time": self.tick_to_time(t.due_tick).isoformat(),
                "completed": t.completed,
                "completed_time": (
                    self.tick_to_time(t.completed_tick).isoformat()
                    if t.completed_tick is not None else None
                ),
                "overdue": self._task_overdue(t),
            })

        shifts = []
        for s in self.shifts:
            hours = self._shift_hours(s)
            shifts.append({
                "shift_id": s.shift_id,
                "zone_id": s.zone_id,
                "worker_id": s.worker_id,
                "start_time": self.tick_to_time(s.start_tick).isoformat(),
                "end_time": self.tick_to_time(s.end_tick).isoformat(),
                "hours_on_shift": hours,
                "active": self._shift_active(s),
                "long_shift": self._shift_active(s) and hours >= LONG_SHIFT_HOURS,
            })

        return {
            "tick": self.tick,
            "timestamp": self.now.isoformat(),
            "note": "SYNTHETIC DATA - not from a real plant",
            "zones": [
                {"zone_id": z.zone_id, "name": z.name, "x": z.x, "y": z.y}
                for z in self.zones
            ],
            "gas_readings": gas_readings,
            "permits": permits,
            "maintenance_tasks": maintenance,
            "shifts": shifts,
        }


# ====================================================================== #
# Pre-built demo scenario
# ====================================================================== #
def build_demo_scenario(seed: int = 42) -> SyntheticPlant:
    """
    Script the exact compound-risk situation we show live on stage.

    Timeline (zone-3, "Process Unit B"):
      tick 10 : a HOT WORK permit opens in zone-3 with NO fire watch logged
      tick 12 : gas in zone-3 begins trending upward
      ~tick 14-16 : gas is clearly rising and a hot work permit is active
                    with no fire watch -> the FUSION layer should already
                    flag a compound risk here...
      tick 18 : ...yet gas only now crosses the single-sensor hard threshold
                (50 ppm). A traditional single-sensor alarm fires no earlier
                than this.
      tick 20 : gas ~65 ppm; the combination is unambiguously dangerous.

    The gap between ~tick 14 (fusion flags) and tick 18 (single-sensor
    alarm) is the whole point: it proves correlation adds value over
    isolated threshold alerting. Ramp is tuned so no single signal crosses
    a hard threshold before tick 18.
    """
    plant = SyntheticPlant(seed=seed)

    # tick 10: hot work permit opens in zone-3, fire watch NOT logged.
    def _open_hot_work(p: SyntheticPlant):
        p.open_permit(Permit(
            permit_id="PTW-3009",
            zone_id="zone-3",
            permit_type="hot_work",
            start_tick=10,
            end_tick=40,
            fire_watch_logged=False,   # the missing safeguard
        ))

    plant.schedule(10, "Open hot work permit in zone-3 (no fire watch)",
                   _open_hot_work)

    # tick 12: gas in zone-3 starts trending up.
    # Ramp math: baseline 10 ppm, rate 7 ppm/tick from tick 12.
    #   tick 17 -> ~45 ppm (still < 50 hard threshold)
    #   tick 18 -> ~52 ppm (crosses 50 -> single-sensor alarm fires)
    #   tick 20 -> ~66 ppm (clearly dangerous)
    # Plateau at 80 ppm to represent a sustained critical band.
    def _start_trend(p: SyntheticPlant):
        p.start_gas_trend("zone-3", rate_ppm_per_tick=7.0, cap_ppm=80.0)

    plant.schedule(12, "Start upward gas trend in zone-3", _start_trend)

    return plant
